image: "python:3.9"

stages:
   - Build
   - Static Analysis
   - Test


install:
  stage: Build
  script:
    - python -m pip install --upgrade pip
    - pip install flake8 black pytest

flake8:
  stage: Static Analysis
  script:
    - flake8 .

black:
  stages: Static Analysis
  script:
    - black

pytest:
  stage: Test
  script:
    - python -m pytest
